### ISSUE TITLE
Update graph reconstruction container location

### ISSUE THREAD

**Issue by mikeyweigand** [CDCgov/polkapox#2]
Embedded container `mpxvgfa.sif` too large for inclusion in `/assets/`. Alternative storage location needed.

**Comment by jessicarowell** [comment]
Submitted to staph-b/docker-builds 2/1/24

**Comment by jessicarowell** [comment]
Container is hosted here: https://hub.docker.com/r/staphb/polkapox
Code has been modified to get the container instead of looking locally.
