### ISSUE TITLE
Pipeline won't run when cdc.config file missing

### ISSUE THREAD

**Issue by jessicarowell** [CDCgov/polkapox#5]
### Description of the bug

Line 184 in nextflow.config causes pipeline to fail because this file has not been included in the `conf` folder.

line 184: `includeConfig 'conf/cdc.config'`

We can remove this line, but then CDC users need to point to the cdc config file when they run the pipeline on Rosalind, and so we need to update README docs to indicate that.  Otherwise, we include that file in `conf`.  I can do whichever is preferred.

### Command used and terminal output

```console
nextflow run main.nf --indir /scicomp/groups-pure/Projects/scbs_mpob/JRowell_ick4/mpox_testing/paired/ --outdir /scicomp/groups-pure/Projects/scbs_mpob/JRowell_ick4/mpox_testing/results/ --project_name test -profile singularity,rosalind

File not found: /scicomp/home-pure/ick4/01.scripts/polkapox/conf/cdc.config
```

### Relevant files

N/A

**Comment by mikeyweigand** [comment]
Suggest to remove `includeConfig 'conf/cdc.config` from `nextflow.config`. Readme already has some basic instruction for CDC users to add their own config:  
https://github.com/CDCgov/polkapox?tab=readme-ov-file#running-on-cdc-cluster

Suggest to update this with generic example of how to also define config at runtime, eg:  
`-config /some/path/to/cdc.config`

**Comment by jessicarowell** [comment]
Done. Waiting to be able to test (missing mpxvgfa.sif)

**Comment by jessicarowell** [comment]
Merged into master by @mikeyweigand
